sudo: required
dist: trusty
language: ruby
cache:
  bundler: true
env:
  - DATABASE_URL="postgresql://postgres@localhost/upsert_test"
rvm:
  - 2.3.1
before_script:
  - createdb --echo -U postgres upsert_test
  - psql -U postgres upsert_test < spec/dummy/db/structure.sql

before_install: gem install bundler

addons:
  postgresql: "9.5"

env:
  - "RAILS_VERSION=5.2"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=master"

allow_failures:
  - env: 'RAILS_VERSION=master'
